# Generated by Django 4.1.13 on 2024-01-26 08:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_category_created_at_category_updated_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='updated_at',
        ),
    ]
