# Generated by Django 4.1.13 on 2024-01-26 09:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_remove_category_updated_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='industry',
        ),
    ]
