# Generated by Django 4.1.13 on 2024-01-27 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_remove_project_budget'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='investment_size',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
